// Prototype logic: world map (D3 + topojson), year slider, category filters, event list.

const CATEGORY_COLORS = {
  "Major Events": "#ffd60a",
  "Wars & Conflicts": "#e5534b",
  "Politics & Government": "#4fb0ff",
  People: "#f2c94c",
  "Science & Technology": "#6fcf97",
  "Exploration & Discovery": "#bb86fc",
  "Religion & Belief Systems": "#f2994a",
  "Economy & Trade": "#56ccf2",
  "Disasters & Pandemics": "#eb5757",
  "Social Movements & Revolutions": "#9b51e0",
  "Architecture & Engineering": "#c0a080",
  "Sports & Entertainment": "#2d9cdb",
  "Empires & Countries": "#20b2aa",
};

const CATEGORY_ORDER = [
  "Major Events",
  "Wars & Conflicts",
  "Politics & Government",
  "People",
  "Science & Technology",
  "Exploration & Discovery",
  "Religion & Belief Systems",
  "Economy & Trade",
  "Disasters & Pandemics",
  "Social Movements & Revolutions",
  "Architecture & Engineering",
  "Sports & Entertainment",
  "Empires & Countries",
];

// One glyph per category, drawn on top of the category-coloured dot so the
// marker carries its meaning even for colour-blind users (several of the 13
// palette colours are hard to tell apart otherwise).
//
// All paths are authored in a 24x24 box and stroked rather than filled --
// stroked outlines stay legible when scaled down to ~11px, where fine filled
// detail turns into mush. Keep any new glyph to a handful of bold strokes.
const CATEGORY_ICONS = {
  // Star
  "Major Events": "M12 4l2.4 5.2 5.6.6-4.2 3.9 1.2 5.5L12 16.4 7 19.2l1.2-5.5L4 9.8l5.6-.6z",
  // Crossed swords
  "Wars & Conflicts": "M6 5l12 12M18 5L6 17M3 19l4-4M21 19l-4-4",
  // Classical building with columns
  "Politics & Government": "M3 21h18M12 3l8 4H4zM6 21V9M10 21V9M14 21V9M18 21V9",
  // Head and shoulders
  People: "M12 8.2a3.1 3.1 0 100-6.2 3.1 3.1 0 000 6.2zM4.8 21c0-4 3.2-7.2 7.2-7.2s7.2 3.2 7.2 7.2",
  // Laboratory flask
  "Science & Technology": "M9 3h6M10 3v6l-5 9a1.8 1.8 0 001.6 2.8h10.8A1.8 1.8 0 0019 18l-5-9V3",
  // Compass needle
  "Exploration & Discovery": "M12 2.5a9.5 9.5 0 100 19 9.5 9.5 0 000-19zM16.2 7.8l-2.6 6.4-6.4 2.6 2.6-6.4z",
  // Domed place of worship
  "Religion & Belief Systems": "M12 2v3M3 21h18M6 21V11a6 6 0 0112 0v10",
  // Coin
  "Economy & Trade": "M12 2.5a9.5 9.5 0 100 19 9.5 9.5 0 000-19zM12 6.5v11M14.8 9.6c0-1.4-1.2-2.1-2.8-2.1s-2.8.8-2.8 2.1 1.3 1.9 2.8 2.3 2.8 1 2.8 2.4-1.2 2.1-2.8 2.1-2.8-.7-2.8-2.1",
  // Warning triangle
  "Disasters & Pandemics": "M12 3l9.5 17H2.5zM12 9v5M12 17.4v.2",
  // Raised flag
  "Social Movements & Revolutions": "M5.5 21V3M5.5 3.5h11l-2.2 4.2 2.2 4.2h-11",
  // Crane / building under construction
  "Architecture & Engineering": "M4 21V7l8-4 8 4v14M9.5 21v-5.5h5V21M8.5 10.5h2M13.5 10.5h2",
  // Trophy
  "Sports & Entertainment": "M8 3.5h8V9a4 4 0 01-8 0zM5 4.5h3M16 4.5h3M12 13v4M9 21h6",
  // Crown
  "Empires & Countries": "M3 8l3.6 11h10.8L21 8l-5 4-4-7-4 7z",
};

const state = {
  year: 1969,
  activeCategories: new Set(CATEGORY_ORDER),
  playing: false,
  playTimer: null,
};

const yearSlider = document.getElementById("yearSlider");
const yearBadge = document.getElementById("yearBadge");
const eventsYearEl = document.getElementById("eventsYear");
const eventsListEl = document.getElementById("eventsList");
const categoryFiltersEl = document.getElementById("categoryFilters");
const stepBackBtn = document.getElementById("stepBack");
const stepForwardBtn = document.getElementById("stepForward");
const playBtn = document.getElementById("playBtn");
const mapSectionEl = document.querySelector(".map-section");
const mapTooltipEl = document.getElementById("mapTooltip");
const datasetStatEl = document.getElementById("datasetStat");
const zoomInBtn = document.getElementById("zoomInBtn");
const zoomOutBtn = document.getElementById("zoomOutBtn");
const zoomResetBtn = document.getElementById("zoomResetBtn");
const mapZoomHintEl = document.getElementById("mapZoomHint");
const discoveryPromptEl = document.getElementById("discoveryPrompt");
const discoveryRefreshBtnEl = document.getElementById("discoveryRefreshBtn");
const discoverGoBtnEl = document.getElementById("discoverGoBtn");
const discoverySectionEl = document.querySelector(".discovery-section");

// The Discover prompt pool lives in data/discover.js, generated by
// scripts/build-discover.mjs and loaded before this file. It's kept out of here
// because it's ~1000 entries: too big to read past, and regenerated rather than
// edited. DISCOVERY_PROMPTS is the global it defines.

// "BC" rather than "BCE" to match the static year pages, which use it because
// it is what people actually search for -- "44 BC" outweighs "44 BCE" by a wide
// margin, and the app links straight through to those pages.
function formatYear(y) {
  return y < 0 ? `${Math.abs(y)} BC` : `${y}`;
}

// ---- Timeline scale ----
//
// The slider used to map position to year linearly, which spent 82.6% of the
// track on 0.58% of the events: 919 events lie before 500 BC, spread over
// 11,980 years, while the other 158,174 were crushed into the remaining 17.4%.
// A pixel near the right-hand end was worth sixteen years, so the entire
// twentieth century sat inside about seven pixels.
//
// So the track is now piecewise. Everything from 500 BC onward gets exactly one
// slider position per year -- arrow keys step a single year, and the dense part
// of history is where nearly all the track goes. The thin pre-500 BC stretch is
// compressed into a tenth of the width, which is still far more room than its
// share of the events would justify, because a timeline that visibly reaches
// back to 12480 BC is worth more than the pixels it costs.
//
// Positions are integers because that is what <input type="range"> steps in.
// state.year stays the source of truth; the slider is only a view of it, so a
// rounded position never feeds back into the year.
const SCALE = { min: -500, max: 2026, split: -500, sparsePositions: 0, positions: 1 };

// Below this year the data is too thin to deserve linear space. 500 BC is where
// the dataset stops being sparse: 919 events before it, 158,174 after.
const SCALE_SPLIT_YEAR = -500;
// Share of the track given to everything before the split.
const SPARSE_TRACK_SHARE = 0.1;

function buildTimelineScale(minYear, maxYear) {
  SCALE.min = minYear;
  SCALE.max = maxYear;
  SCALE.split = Math.max(minYear, Math.min(SCALE_SPLIT_YEAR, maxYear));
  const densePositions = Math.max(1, SCALE.max - SCALE.split);
  // No sparse region at all when the dataset starts after the split, which keeps
  // this correct if the earliest event ever moves forward.
  SCALE.sparsePositions =
    SCALE.split > minYear ? Math.max(1, Math.round((densePositions * SPARSE_TRACK_SHARE) / (1 - SPARSE_TRACK_SHARE))) : 0;
  SCALE.positions = SCALE.sparsePositions + densePositions;
}

function posToYear(pos) {
  const p = Math.min(Math.max(Math.round(pos), 0), SCALE.positions);
  if (p >= SCALE.sparsePositions) return SCALE.split + (p - SCALE.sparsePositions);
  return Math.round(SCALE.min + ((SCALE.split - SCALE.min) * p) / SCALE.sparsePositions);
}

function yearToPos(year) {
  const y = Math.min(Math.max(year, SCALE.min), SCALE.max);
  if (y >= SCALE.split) return SCALE.sparsePositions + (y - SCALE.split);
  return Math.round(((y - SCALE.min) / (SCALE.split - SCALE.min)) * SCALE.sparsePositions);
}

// An event carries `prec` only when Wikidata's own date is vaguer than a year:
// 6 millennium, 7 century, 8 decade. Wikidata renders such a date as a concrete
// January 1st, so "12th century" reaches us as 1101 or 1150 depending on the
// item, and thousands of events piled onto those anchor years looking exact.
//
// They still sit at the anchor year on the timeline -- it's the only position we
// have, and it's right to within a century -- but the event list says what the
// source actually claims rather than parroting the anchor. Kept in step with
// precisionLabel() in scripts/build-year-pages.mjs.
const ordinalSuffix = (n) => {
  const r = n % 100;
  if (r >= 11 && r <= 13) return `${n}th`;
  return `${n}${{ 1: "st", 2: "nd", 3: "rd" }[n % 10] || "th"}`;
};

// Wikibase derives the ordinal from the astronomical year (the one where 0 exists
// and means 1 BC), so -0400 at century precision is "4th century BC" in Wikidata's
// own renderer. We store display years, so convert back before the arithmetic or
// every BC label lands one century out. Kept in step with precisionLabel() in
// scripts/build-year-pages.mjs.
function precisionLabel(e) {
  if (!e.prec) return null;
  const a = e.year < 0 ? e.year + 1 : e.year;
  const bc = a <= 0;
  const mag = Math.abs(a);
  if (e.prec === 8) return `${Math.floor(mag / 10) * 10}s${bc ? " BC" : ""}`;
  const size = e.prec === 7 ? 100 : 1000;
  const word = e.prec === 7 ? "century" : "millennium";
  return `${ordinalSuffix(Math.max(1, Math.ceil(mag / size)))} ${word}${bc ? " BC" : ""}`;
}

// ---- Data access ----
//
// The dataset is 111,389 events / 28MB. Shipping all of it before the first
// paint cost about six seconds on a good connection and far worse on a phone,
// so scripts/build-chunks.mjs splits it into a 27KB index plus 69 era chunks
// fetched on demand. The map only ever displays one year, and a year is never
// split across chunks, so a render touches exactly one of them.
//
// INDEX holds every year that has events together with a bitmask of which
// categories appear in it. That is deliberately enough to drive the slider, the
// step/play buttons and the nearest-year hint *synchronously* -- those have to
// answer "which years have anything" across the whole timeline, and making them
// wait on the network would feel broken.

let INDEX = null;
let catBit = new Map(); // category name -> its bit position in the year mask

// Resolved chunks and in-flight requests are tracked separately so callers can
// ask "is this already here?" without going through a promise. Awaiting even an
// already-resolved promise costs a microtask, and that is enough to make the
// slider visibly trail the handle while dragging.
const chunkData = new Map();
const chunkPending = new Map();

// Roughly 18,000 events held at once. Scrubbing the full timeline would
// otherwise accumulate all 69 chunks, and 28MB of JSON inflates to well over
// 100MB once parsed into objects -- enough to get the tab killed on a phone.
const MAX_CACHED_CHUNKS = 12;

const chunkUrl = (n) => `data/events/${String(n).padStart(3, "0")}.json`;

async function loadIndex() {
  const res = await fetch("data/index.json");
  if (!res.ok) throw new Error(`data/index.json: HTTP ${res.status}`);
  INDEX = await res.json();
  catBit = new Map(INDEX.categories.map((c, i) => [c, i]));
}

// chunkStarts ascends and the ranges tile the timeline with no gaps, so the
// chunk holding a year is the last one starting at or before it. Binary search
// because this runs on every slider tick.
function chunkForYear(year) {
  const starts = INDEX.chunkStarts;
  if (year <= starts[0]) return 0;
  let lo = 0;
  let hi = starts.length - 1;
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1;
    if (starts[mid] <= year) lo = mid;
    else hi = mid - 1;
  }
  return lo;
}

function loadChunk(n) {
  const have = chunkData.get(n);
  if (have) return Promise.resolve(have);
  const inFlight = chunkPending.get(n);
  if (inFlight) return inFlight;

  const p = fetch(chunkUrl(n))
    .then((res) => {
      if (!res.ok) throw new Error(`${chunkUrl(n)}: HTTP ${res.status}`);
      return res.json();
    })
    .then((rows) => {
      chunkPending.delete(n);
      chunkData.set(n, rows);
      // Map iterates in insertion order, so the first key is the oldest.
      while (chunkData.size > MAX_CACHED_CHUNKS) {
        chunkData.delete(chunkData.keys().next().value);
      }
      return rows;
    })
    .catch((err) => {
      // Forget the failure rather than caching it, so scrubbing back to this
      // era retries instead of showing the same error forever.
      chunkPending.delete(n);
      throw err;
    });

  chunkPending.set(n, p);
  return p;
}

// Warm the neighbours so stepping or playing across a chunk boundary doesn't
// stall. Failures here are irrelevant -- the real render will retry and report.
function prefetchNeighbours(n) {
  for (const m of [n + 1, n - 1]) {
    if (m >= 0 && m < INDEX.chunkStarts.length && !chunkData.has(m) && !chunkPending.has(m)) {
      loadChunk(m).catch(() => {});
    }
  }
}

function activeMask() {
  let mask = 0;
  for (const c of state.activeCategories) {
    const bit = catBit.get(c);
    if (bit !== undefined) mask |= 1 << bit;
  }
  return mask;
}

// Years carrying at least one event in an active category. Already ascending in
// the index, so no sort is needed.
function getEventYears() {
  if (!INDEX) return [];
  const mask = activeMask();
  if (!mask) return [];
  const out = [];
  for (const [y, m] of INDEX.years) if (m & mask) out.push(y);
  return out;
}

// Builds a marker-lookalike swatch (coloured disc + category glyph) for use in
// the filter list and the pinned event card.
function categorySwatch(cat, size = 18) {
  const svgNS = "http://www.w3.org/2000/svg";
  const iconSize = size * 0.6875; // matches the map's 8:11 dot-to-glyph ratio
  const svg = document.createElementNS(svgNS, "svg");
  svg.setAttribute("class", "chip-dot");
  svg.setAttribute("width", size);
  svg.setAttribute("height", size);
  svg.setAttribute("viewBox", `${-size / 2} ${-size / 2} ${size} ${size}`);
  svg.setAttribute("aria-hidden", "true");

  const circle = document.createElementNS(svgNS, "circle");
  circle.setAttribute("r", size / 2 - 0.75);
  circle.setAttribute("fill", CATEGORY_COLORS[cat] || "#888");
  svg.appendChild(circle);

  if (CATEGORY_ICONS[cat]) {
    const g = document.createElementNS(svgNS, "g");
    g.setAttribute("transform", `translate(${-iconSize / 2},${-iconSize / 2}) scale(${iconSize / 24})`);
    const p = document.createElementNS(svgNS, "path");
    p.setAttribute("d", CATEGORY_ICONS[cat]);
    g.appendChild(p);
    svg.appendChild(g);
  }
  return svg;
}

function buildCategoryFilters() {
  categoryFiltersEl.innerHTML = "";
  CATEGORY_ORDER.forEach((cat) => {
    const id = `cat-${cat.replace(/[^a-z0-9]/gi, "")}`;
    const wrapper = document.createElement("label");
    wrapper.className = "chip";
    wrapper.setAttribute("for", id);

    const checkbox = document.createElement("input");
    checkbox.type = "checkbox";
    checkbox.className = "chip-input";
    checkbox.id = id;
    checkbox.checked = state.activeCategories.has(cat);
    checkbox.addEventListener("change", () => {
      if (checkbox.checked) state.activeCategories.add(cat);
      else state.activeCategories.delete(cat);
      renderAll();
    });

    // The swatch shows the same colour *and* glyph as the map marker, so the
    // filter list doubles as the map legend -- 13 glyphs is more than anyone
    // will memorise from the map alone.
    const swatch = categorySwatch(cat);

    wrapper.appendChild(checkbox);
    wrapper.appendChild(swatch);
    wrapper.appendChild(document.createTextNode(cat));
    categoryFiltersEl.appendChild(wrapper);
  });
}

document.getElementById("selectAll").addEventListener("click", () => {
  state.activeCategories = new Set(CATEGORY_ORDER);
  buildCategoryFilters();
  renderAll();
});

document.getElementById("clearAll").addEventListener("click", () => {
  state.activeCategories = new Set();
  buildCategoryFilters();
  renderAll();
});

function renderEventsList(currentEvents) {
  eventsYearEl.textContent = formatYear(state.year);
  eventsListEl.innerHTML = "";

  if (currentEvents.length === 0) {
    const nearestInfo = findNearestEventYear(state.year);
    const empty = document.createElement("div");
    empty.className = "empty-state";
    empty.textContent = nearestInfo
      ? `No recorded events in ${formatYear(state.year)}. Nearest: ${formatYear(nearestInfo)} — use the arrows to jump there.`
      : `No events match the selected focus areas.`;
    eventsListEl.appendChild(empty);
    return;
  }

  // Events actually dated to this year first. The rest are only dated to a
  // century or decade and merely anchor here, so they shouldn't outrank the
  // year's real content -- on 1101 they outnumber it roughly 75 to 1.
  const ordered = [...currentEvents].sort((a, b) => (a.prec ? 1 : 0) - (b.prec ? 1 : 0));

  ordered.forEach((e) => {
    const card = document.createElement("div");
    card.className = "event-card";
    card.style.borderLeftColor = CATEGORY_COLORS[e.category] || "#888";

    const isWikidata = e.source === "wikidata";
    const approx = precisionLabel(e);
    const approxTag = approx
      ? `<span class="event-approx" title="Dated only to the ${approx} in the source data, not to ${formatYear(e.year)}">${approx}</span>`
      : "";
    card.innerHTML = `
      <h3>${e.title}</h3>
      <div class="event-meta"><span class="event-meta-swatch"></span>${e.category}${e.location ? ` &middot; ${e.location}` : ""}${approxTag}</div>
      ${e.summary ? `<p class="event-summary">${e.summary}</p>` : ""}
      <a href="${e.wiki}" target="_blank" rel="noopener noreferrer">${isWikidata ? "View source on Wikidata" : "Read more on Wikipedia"} &rarr;</a>
    `;
    // Same glyph as the map marker and the filter legend, so a category is
    // recognisable in all three places.
    card.querySelector(".event-meta-swatch").appendChild(categorySwatch(e.category, 14));
    eventsListEl.appendChild(card);
  });
}

// Points at the static page for whatever year is on screen. It's the only link
// from the app into /year/, which matters twice over: a reader gets a plain
// readable version of the year they're looking at, and a crawler that lands on
// "/" finds its way into the 2,451 year pages instead of seeing one page of
// JavaScript.
const yearPageLinkEl = document.getElementById("yearPageLink");
function yearSlug(y) {
  return y < 0 ? `${Math.abs(y)}-bc` : String(y);
}
function updateYearPageLink() {
  if (!yearPageLinkEl) return;
  yearPageLinkEl.href = `/year/${yearSlug(state.year)}/`;
  yearPageLinkEl.textContent = `Full ${formatYear(state.year)} page →`;
}

function findNearestEventYear(year) {
  const years = getEventYears();
  if (years.length === 0) return null;
  return years.reduce((best, y) =>
    Math.abs(y - year) < Math.abs(best - year) ? y : best
  );
}

// ---- Map rendering ----

let projection, path, svg, zoomLayer, markerLayer, zoomBehavior;
let currentZoomK = 1;
// Dots are bigger than the old r=5 so a glyph fits legibly inside them.
const MARKER_R = 8;
const ICON_SIZE = 11;

// Stable identity for an event. Title alone isn't unique (see renderMarkers).
const eventKey = (d) => `${d.year}|${d.title}|${d.lat}|${d.lng}`;
// Title of the marker currently spotlighted by Discover, if any.
let spotlightKey = null;
const MAP_WIDTH = 960;
const MAP_HEIGHT = 500;

// Markers are drawn in viewBox units and scaled by 1/zoom so they stay a
// constant size on screen as you zoom. That holds on desktop, where the 960-unit
// viewBox renders at roughly 960px. On a 375px phone the same viewBox is scaled
// to 0.39, so the 11-unit halo lands as an 8.6px tap target -- a fifth of the
// ~44px a fingertip needs, on the one control the whole page exists to offer.
//
// Scaling the marker layer back up on phones costs nothing on the map itself:
// dots already overlap at this size and the existing fan-out handles co-located
// ones. Read on each use rather than cached, so rotating the phone or resizing
// picks up the change without a reload.
const markerScale = () => (window.matchMedia("(max-width: 640px)").matches ? 2 : 1);

function initMap() {
  svg = d3
    .select("#map")
    .append("svg")
    .attr("viewBox", `0 0 ${MAP_WIDTH} ${MAP_HEIGHT}`);

  projection = d3.geoNaturalEarth1().scale(160).translate([MAP_WIDTH / 2, MAP_HEIGHT / 2]);
  path = d3.geoPath(projection);

  // A hatch rather than a flat fill. Thirteen category colours are already in
  // play on this map, and a fourteenth solid colour would read as another
  // category; diagonal stripes read as "provisional" in every atlas ever
  // printed. patternUnits is userSpaceOnUse so the stripes stay put against the
  // map rather than shifting inside each shape.
  const defs = svg.append("defs");
  const hatch = defs
    .append("pattern")
    .attr("id", "disputedHatch")
    .attr("patternUnits", "userSpaceOnUse")
    .attr("width", 9)
    .attr("height", 9)
    .attr("patternTransform", "rotate(45)");
  // Deliberately faint. This is a footnote on the map, not a category: it should
  // be findable when you look for it and invisible when you are not. Wider
  // spacing and a thinner, dimmer line read as texture rather than as a fill.
  hatch.append("rect").attr("width", 9).attr("height", 9).attr("fill", "none");
  hatch.append("line").attr("x1", 0).attr("y1", 0).attr("x2", 0).attr("y2", 9).attr("stroke", "rgba(255, 255, 255, 0.16)").attr("stroke-width", 0.8);

  zoomLayer = svg.append("g").attr("class", "zoom-layer");
  const landLayer = zoomLayer.append("g").attr("class", "land-layer");
  // Between the land and the markers: over the country fills so the hatch is
  // visible, under the markers so it never sits on top of a dot.
  disputedLayer = zoomLayer.append("g").attr("class", "disputed-layer");
  markerLayer = zoomLayer.append("g").attr("class", "marker-layer");

  zoomBehavior = d3
    .zoom()
    .scaleExtent([1, 14])
    .translateExtent([
      [0, 0],
      [MAP_WIDTH, MAP_HEIGHT],
    ])
    .extent([
      [0, 0],
      [MAP_WIDTH, MAP_HEIGHT],
    ])
    .on("start", () => {
      svg.classed("zooming", true);
      dismissZoomHint();
    })
    .on("zoom", (event) => {
      currentZoomK = event.transform.k;
      zoomLayer.attr("transform", event.transform);
      markerLayer.selectAll(".marker-visual").attr("transform", `scale(${markerScale() / currentZoomK})`);
      // Fan offsets are screen-space, so they are divided by the zoom factor and
      // have to be recomputed here or co-located markers drift apart as you zoom.
      if (markerFanOffsets.size) markerLayer.selectAll("g.event-marker").attr("transform", markerTransform);
      scheduleLabelReflow();
    })
    .on("end", () => {
      svg.classed("zooming", false);
    });

  svg.call(zoomBehavior);

  zoomInBtn?.addEventListener("click", () => {
    dismissZoomHint();
    svg.transition().duration(220).call(zoomBehavior.scaleBy, 1.6);
  });
  zoomOutBtn?.addEventListener("click", () => {
    dismissZoomHint();
    svg.transition().duration(220).call(zoomBehavior.scaleBy, 1 / 1.6);
  });
  zoomResetBtn?.addEventListener("click", () => {
    dismissZoomHint();
    svg.transition().duration(300).call(zoomBehavior.transform, d3.zoomIdentity);
  });

  d3.json("https://cdn.jsdelivr.net/npm/world-atlas@2/countries-110m.json").then((world) => {
    const countries = topojson.feature(world, world.objects.countries);
    landLayer
      .selectAll("path")
      .data(countries.features)
      .join("path")
      .attr("class", "land")
      .attr("d", path);
    drawDisputedAreas();
    renderAll();
  });
}

// Territories whose sovereignty is contested, drawn over the country shapes in a
// hatch so they read as "this is not settled" rather than as another country.
//
// The base atlas draws one set of present-day borders and says nothing about
// which of them anyone disagrees with. It happens to carry Taiwan, Palestine,
// Kosovo, W. Sahara, N. Cyprus and Somaliland as separate shapes, but not
// Kashmir, Crimea, the Golan Heights or Nagorno-Karabakh -- those are folded
// into a neighbour. Marking only the ones the atlas happened to split out would
// have looked like an editorial line rather than an omission, which is worse
// than marking none, so this layer comes from Natural Earth's dedicated
// disputed-areas dataset instead, which carries all 79.
//
// Carries, not shows. About half render to under a pixel at world scale --
// Gibraltar, the Spratlys, Scarborough Reef, Hans Island, Rockall, Mount Scopus
// and 30-odd others are territories whose whole point is that they are tiny.
// Zoom is an SVG transform over already-projected paths, so those stay invisible
// at every zoom level rather than growing into view. They are in the data, they
// are hoverable where the geometry is big enough to hit, and the layer should
// not be described as showing them.
//
// The label is Natural Earth's own wording -- "Admin. by India; Claimed by
// Pakistan" -- rather than anything written here. Who administers a territory
// and who claims it are both checkable facts, and stating both is the only
// position this site is entitled to take.
function drawDisputedAreas() {
  if (!disputedLayer) return;
  d3.json("data/disputed-areas.json?v=cd489899")
    .then((fc) => {
      disputedLayer
        .selectAll("path")
        .data(fc.features)
        .join("path")
        .attr("class", "disputed-area")
        .attr("d", path)
        .append("title")
        .text((d) => (d.properties.d ? `${d.properties.n} — ${d.properties.d}` : d.properties.n));
    })
    .catch(() => {
      // A missing overlay is not worth breaking the map for; the countries are
      // already drawn and every marker still works without it.
    });
}

function dismissZoomHint() {
  mapZoomHintEl?.classList.add("hidden");
}

let labelReflowTimer = null;
function scheduleLabelReflow() {
  clearTimeout(labelReflowTimer);
  labelReflowTimer = setTimeout(resolveLabelCollisions, 120);
}

// Events sharing an exact coordinate, fanned into rings so each one can be
// clicked.
//
// Nearly half the dataset sits on a coordinate shared with another event --
// 1,446 events are pinned to "London", 1,008 to "Rome" -- because a battle is
// placed at its named location's centre, not where it was fought. In a single
// year that still stacks up: 5,267 year-and-place combinations hold more than
// one event, the worst being 46 markers on Rome in 101 BC. Stacked exactly, only
// the topmost is hoverable and the rest are unreachable on the map entirely.
//
// The offset is in screen pixels, applied to the outer group divided by the zoom
// factor so the fan stays the same size on screen at every zoom level. That is
// deliberate rather than lazy: these markers are at the *same* coordinate, so
// unlike genuinely-nearby markers no amount of zooming can ever separate them,
// and a fan that grew with zoom would just fly apart.
//
// Ring k holds 6k slots at radius k*FAN_STEP, first event in the centre, which
// puts 46 markers inside four rings.
const FAN_STEP = 18;

function fanOffsets(events) {
  const byPoint = new Map();
  for (const d of events) {
    // Rounded, not exact. The same city reaches us at more than one precision --
    // Rome is both 41.893055555,12.482777777 and 41.89,12.48 -- and grouping on
    // the exact pair built two separate fans that then sat on top of each other.
    // 0.01 degrees is about a kilometre, which is under a third of a pixel even
    // at maximum zoom, so nothing visually distinct is ever merged by this.
    const k = `${Math.round(d.lat * 100)},${Math.round(d.lng * 100)}`;
    let arr = byPoint.get(k);
    if (!arr) byPoint.set(k, (arr = []));
    arr.push(d);
  }

  const offsets = new Map();
  for (const arr of byPoint.values()) {
    if (arr.length === 1) continue;
    // Every member fans around one shared centre rather than around its own
    // coordinate. Members of a group are within 0.01 degrees of each other but
    // not identical, and offsetting each from its own point left the ring
    // spacing slightly uneven -- enough for neighbouring dots to cover each
    // other's centre, which is the exact problem being solved here.
    const base = { lat: arr[0].lat, lng: arr[0].lng };
    // Sorted so the arrangement is stable: the same year re-rendered after a
    // filter change must not shuffle the markers around under the cursor.
    arr.sort((a, b) => (a.title < b.title ? -1 : a.title > b.title ? 1 : 0));
    let i = 0;
    for (const d of arr) {
      if (i === 0) {
        offsets.set(eventKey(d), { base, dx: 0, dy: 0 });
        i++;
        continue; // first one holds the centre of the ring
      }
      // Which ring this index lands in, and where around it.
      let ring = 1;
      let seen = 1;
      while (seen + 6 * ring <= i) {
        seen += 6 * ring;
        ring++;
      }
      const slot = i - seen;
      const angle = (slot / (6 * ring)) * 2 * Math.PI - Math.PI / 2;
      offsets.set(eventKey(d), {
        base,
        dx: Math.cos(angle) * ring * FAN_STEP,
        dy: Math.sin(angle) * ring * FAN_STEP,
      });
      i++;
    }
  }
  return offsets;
}

// Offsets for the markers currently on screen. Held at module scope because the
// zoom handler has to re-apply them: they are divided by the zoom factor, so
// they change whenever it does.
let markerFanOffsets = new Map();

function markerTransform(d) {
  const coords = projection([d.lng, d.lat]);
  if (!coords) return "translate(-100,-100)";
  const off = markerFanOffsets.get(eventKey(d));
  if (!off) return `translate(${coords[0]}, ${coords[1]})`;
  const b = projection([off.base.lng, off.base.lat]) || coords;
  return `translate(${b[0] + off.dx / currentZoomK}, ${b[1] + off.dy / currentZoomK})`;
}

function renderMarkers(currentEvents) {
  if (!markerLayer) return;
  markerFanOffsets = fanOffsets(currentEvents);
  // The marker set is changing, so any pinned card may point at an event
  // that's about to disappear -- always clear it, pinned or not. Same reasoning
  // for the Discover spotlight; jumpToEvent() re-applies it after this render.
  unpinMapTooltip();
  clearSpotlight();

  // Keyed on more than the title: ~300 titles in the dataset are genuinely
  // shared by two events in the same year (several Roman consuls share a name,
  // and cities were besieged repeatedly). Keying on title alone silently
  // collapsed those into a single marker, losing ~455 of them.
  const groups = markerLayer.selectAll("g.event-marker").data(currentEvents, eventKey);

  groups.exit().remove();

  const entered = groups
    .enter()
    .append("g")
    .attr("class", "event-marker")
    .attr("transform", markerTransform);

  // Visuals live in a nested group that's counter-scaled against the current
  // zoom level, so dots/labels stay a constant pixel size while geographic
  // distance between them grows as you zoom in -- that's what lets zoom
  // actually pull overlapping markers apart instead of just magnifying them.
  const visual = entered.append("g").attr("class", "marker-visual").attr("transform", `scale(${markerScale() / currentZoomK})`);

  visual.append("circle").attr("class", "marker-halo").attr("r", 11);
  visual.append("circle").attr("r", MARKER_R);
  // The glyph is authored in a 24x24 box, so scale it down and re-centre it on
  // the dot. Kept as a sibling of the dot (not a child) so the existing
  // circle-based selectors and the spotlight's r animation keep working.
  visual
    .append("g")
    .attr("class", "marker-icon")
    .attr("transform", `translate(${-ICON_SIZE / 2},${-ICON_SIZE / 2}) scale(${ICON_SIZE / 24})`)
    .append("path")
    .attr("d", (d) => CATEGORY_ICONS[d.category] || "");
  visual
    .append("text")
    .attr("class", "marker-label")
    .attr("x", MARKER_R + 5)
    .attr("y", 4)
    .text((d) => d.title);

  entered
    .on("mouseenter", (event, d) => showMapTooltip(event, d))
    .on("mousemove", (event) => {
      if (!isTooltipPinned()) positionMapTooltip(event);
    })
    .on("mouseleave", hideMapTooltip)
    .on("click", (event, d) => {
      // Stop the click reaching the document-level dismiss handler below.
      event.stopPropagation();
      pinMapTooltip(event, d);
    });

  const merged = entered.merge(groups).attr("transform", markerTransform);

  // Markers of deselected categories stay visible but greyed; the actual grey
  // is in CSS, which beats these presentation attributes.
  merged.classed("inactive", (d) => !state.activeCategories.has(d.category));
  merged.select(".marker-visual circle:last-of-type").attr("fill", (d) => CATEGORY_COLORS[d.category] || "#4fb0ff");
  merged.select(".marker-visual .marker-halo").attr("stroke", (d) => CATEGORY_COLORS[d.category] || "#4fb0ff");

  resolveLabelCollisions();
}

// Tries a handful of positions around each dot (right, left, above, below) and
// hides the label (keeping just the dot + hover tooltip) if none are free.
const LABEL_OFFSETS = [
  { dx: MARKER_R + 5, dy: 4, anchor: "start" },
  { dx: -(MARKER_R + 5), dy: 4, anchor: "end" },
  { dx: MARKER_R + 5, dy: -10, anchor: "start" },
  { dx: MARKER_R + 5, dy: 18, anchor: "start" },
  { dx: -(MARKER_R + 5), dy: -10, anchor: "end" },
  { dx: -(MARKER_R + 5), dy: 18, anchor: "end" },
];

function resolveLabelCollisions() {
  const groups = markerLayer.selectAll("g.event-marker").nodes();

  // Seed with each *active* dot's own footprint (tagged with its owning node)
  // so labels route around neighboring markers, not just around each other's
  // text. Each marker's own dot is excluded when checking its own label.
  // Marker positions are stored in pre-zoom map coordinates, but marker
  // *visuals* (dot + label) are counter-scaled to stay a constant pixel
  // size -- so to compare footprints in the same "pixel space" we scale
  // each marker's local position by the current zoom factor. Translation
  // from panning cancels out in the overlap comparison, so it's ignored.
  //
  // Greyed-out dots are deliberately NOT obstacles. They're still drawn (as
  // faint geographic context), but treating them as blockers meant narrowing
  // the filter down to one category produced *zero* labels: at a busy year the
  // few surviving markers sit inside a cluster of a couple hundred greyed dots,
  // and every candidate offset collided with one. A label crossing a 45%-opacity
  // grey dot is a far smaller cost than no label at all.
  const dotRadius = MARKER_R + 2;
  const localXY = (g) => {
    const matrix = g.transform.baseVal.consolidate();
    return {
      x: (matrix ? matrix.matrix.e : 0) * currentZoomK,
      y: (matrix ? matrix.matrix.f : 0) * currentZoomK,
    };
  };
  const placedRects = groups
    .filter((g) => !g.classList.contains("inactive"))
    .map((g) => {
      const { x, y } = localXY(g);
      return {
        owner: g,
        x1: x - dotRadius,
        y1: y - dotRadius,
        x2: x + dotRadius,
        y2: y + dotRadius,
      };
    });

  const sorted = groups.slice().sort((a, b) => localXY(a).x - localXY(b).x);

  // Labels are full event titles, some of which are very long, so a label
  // anchored near an edge can easily run outside the map. The overlap test
  // above works in a pan-independent space, so for the edge test we fall back
  // to real screen rects, which account for zoom and pan automatically.
  const svgRect = svg.node().getBoundingClientRect();

  sorted.forEach((g) => {
    const text = g.querySelector(".marker-label");
    if (!text) return;
    const { x: px, y: py } = localXY(g);

    // Greyed-out (deselected) markers never get a label -- they're context, not
    // content. They're also not obstacles for anyone else's label; see the
    // placedRects seed above for why.
    if (g.classList.contains("inactive")) {
      text.style.display = "none";
      return;
    }

    text.style.display = "";
    let placed = false;

    for (const offset of LABEL_OFFSETS) {
      text.setAttribute("x", offset.dx);
      text.setAttribute("y", offset.dy);
      text.setAttribute("text-anchor", offset.anchor);
      const bbox = text.getBBox();
      const rect = {
        x1: px + bbox.x - 3,
        y1: py + bbox.y - 3,
        x2: px + bbox.x + bbox.width + 3,
        y2: py + bbox.y + bbox.height + 3,
      };
      const overlaps = placedRects.some(
        (r) => r.owner !== g && rect.x1 < r.x2 && rect.x2 > r.x1 && rect.y1 < r.y2 && rect.y2 > r.y1
      );
      const screen = text.getBoundingClientRect();
      const outOfBounds =
        screen.left < svgRect.left ||
        screen.right > svgRect.right ||
        screen.top < svgRect.top ||
        screen.bottom > svgRect.bottom;
      if (!overlaps && !outOfBounds) {
        placedRects.push({ owner: g, ...rect });
        placed = true;
        break;
      }
    }

    if (!placed) {
      text.style.display = "none";
    }
  });
}

// ---- Map hover tooltip ----

// Thumbnail images aren't stored in the dataset (adding one per event would
// balloon the already-18MB data file); instead we lazily fetch them from
// Wikipedia's public REST summary API on hover and cache the result in
// memory so re-hovering the same marker is instant and only fetched once.
const tooltipImageCache = new Map(); // wiki url -> image url | null
let tooltipHoverToken = 0;

function wikipediaTitleFromUrl(url) {
  try {
    const u = new URL(url);
    if (!/(^|\.)wikipedia\.org$/.test(u.hostname)) return null;
    const match = /^\/wiki\/(.+)$/.exec(u.pathname);
    return match ? decodeURIComponent(match[1]) : null;
  } catch {
    return null;
  }
}

async function fetchTooltipImage(d) {
  if (tooltipImageCache.has(d.wiki)) return tooltipImageCache.get(d.wiki);
  const title = wikipediaTitleFromUrl(d.wiki);
  if (!title) {
    tooltipImageCache.set(d.wiki, null);
    return null;
  }
  try {
    const res = await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title)}`);
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const json = await res.json();
    const img = json.thumbnail?.source || null;
    tooltipImageCache.set(d.wiki, img);
    return img;
  } catch {
    tooltipImageCache.set(d.wiki, null);
    return null;
  }
}

function applyTooltipImage(token, imgUrl, event) {
  if (token !== tooltipHoverToken) return; // hover moved on before fetch resolved
  const wrap = document.getElementById("tooltipImageWrap");
  if (!wrap) return;
  if (imgUrl) {
    wrap.innerHTML = `<img src="${imgUrl}" alt="" class="tooltip-image">`;
  } else {
    wrap.innerHTML = "";
  }
  positionMapTooltip(event);
}

// A pinned tooltip (set by clicking a marker) stays put and becomes
// interactive, so the user can actually click through to the source link.
// While pinned it takes precedence over hover, and is dismissed by the close
// button, Escape, clicking outside it, or the marker set being re-rendered.
let pinnedEventKey = null;

function isTooltipPinned() {
  return pinnedEventKey !== null;
}

function tooltipMarkup(d, pinned) {
  const linkText = d.source === "wikidata" ? "View source on Wikidata" : "Read more on Wikipedia";
  const active = state.activeCategories.has(d.category);
  // "Only" is a shortcut for clearing every other checkbox in the filter panel,
  // which is otherwise twelve clicks. Once it has been used the same button has
  // to undo itself, or the card offers no way back and the filter list is the
  // only route out.
  const solo = state.activeCategories.size === 1 && active;
  return `
    <div class="tooltip-image-wrap" id="tooltipImageWrap"></div>
    ${pinned ? `<button class="tooltip-close" id="tooltipClose" aria-label="Close" title="Close">&times;</button>` : ""}
    <h4>${d.title}</h4>
    <div class="tooltip-meta">
      <span class="tooltip-swatch" id="tooltipSwatch"></span>
      <span>${precisionLabel(d) || formatYear(d.year)} &middot; ${d.category}${d.location ? ` &middot; ${d.location}` : ""}</span>
    </div>
    ${d.summary ? `<p class="tooltip-summary">${d.summary}</p>` : ""}
    ${
      pinned
        ? `<a class="tooltip-link" href="${d.wiki}" target="_blank" rel="noopener noreferrer">${linkText} &rarr;</a>
           <button class="tooltip-category-toggle" id="tooltipCategorySolo">
             ${solo ? "Show all categories again" : `Show only &ldquo;${d.category}&rdquo;`}
           </button>
           <button class="tooltip-category-toggle" id="tooltipCategoryToggle">
             ${active ? `Hide &ldquo;${d.category}&rdquo; on map` : `Show &ldquo;${d.category}&rdquo; again`}
           </button>`
        : `<p class="tooltip-hint">Click to keep open</p>`
    }
  `;
}

// Where the pinned card is anchored. Kept so the card can be re-rendered in
// place (e.g. after toggling its category) without needing a fresh mouse event.
let pinnedAnchor = null;
let pinnedEvent = null;

function renderMapTooltip(anchor, d, pinned) {
  const token = ++tooltipHoverToken;
  mapTooltipEl.innerHTML = tooltipMarkup(d, pinned);
  mapTooltipEl.classList.toggle("pinned", pinned);
  mapTooltipEl.classList.add("visible");
  positionMapTooltip(anchor);

  // Marker-matching swatch, built with the same helper as the filter list.
  document.getElementById("tooltipSwatch")?.appendChild(categorySwatch(d.category, 14));

  if (pinned) {
    document.getElementById("tooltipClose")?.addEventListener("click", (e) => {
      e.stopPropagation();
      unpinMapTooltip();
    });
    document.getElementById("tooltipCategoryToggle")?.addEventListener("click", (e) => {
      e.stopPropagation();
      toggleCategoryFromCard(d);
    });
    document.getElementById("tooltipCategorySolo")?.addEventListener("click", (e) => {
      e.stopPropagation();
      soloCategoryFromCard(d);
    });
  }

  // Only for a card the user deliberately opened.
  //
  // This used to run on hover too, which meant dragging the cursor across a busy
  // region sent a stream of article titles to en.wikipedia.org -- events the
  // visitor never chose to look at. /privacy/ said images load "only for events
  // you actually open", and that was simply untrue: renderMapTooltip is called
  // with pinned=false from showMapTooltip, which is bound to mouseenter.
  //
  // Fixed here rather than by rewriting the policy, because the policy describes
  // the behaviour we want. A cached image still shows on hover, since that costs
  // no request.
  if (tooltipImageCache.has(d.wiki)) {
    applyTooltipImage(token, tooltipImageCache.get(d.wiki), anchor);
  } else if (pinned) {
    fetchTooltipImage(d).then((img) => applyTooltipImage(token, img, anchor));
  }
}

// Toggles the pinned event's category and re-pins the same card in place.
// renderAll() clears the pin (the marker set may have changed underneath it),
// so the card has to be restored afterwards rather than left to survive.
function toggleCategoryFromCard(d) {
  if (state.activeCategories.has(d.category)) state.activeCategories.delete(d.category);
  else state.activeCategories.add(d.category);

  const anchor = pinnedAnchor;
  buildCategoryFilters();
  renderAll();
  if (anchor) pinMapTooltip(anchor, d);
}

// Narrows the map to just this card's category, and restores everything when
// pressed a second time. Repinning matters more here than for the hide toggle:
// soloing removes most of the markers on screen, so without the card staying
// put the user loses both the event they were reading and the way back.
function soloCategoryFromCard(d) {
  const solo = state.activeCategories.size === 1 && state.activeCategories.has(d.category);
  state.activeCategories = solo ? new Set(CATEGORY_ORDER) : new Set([d.category]);

  const anchor = pinnedAnchor;
  buildCategoryFilters();
  renderAll();
  if (anchor) pinMapTooltip(anchor, d);
}

function showMapTooltip(anchor, d) {
  if (isTooltipPinned()) return; // don't let hover clobber a pinned card
  renderMapTooltip(anchor, d, false);
}

function pinMapTooltip(anchor, d) {
  pinnedEventKey = eventKey(d);
  // positionMapTooltip() only reads clientX/clientY, so a plain point works and
  // survives the re-render that a category toggle triggers.
  pinnedAnchor = { clientX: anchor.clientX, clientY: anchor.clientY };
  pinnedEvent = d;
  renderMapTooltip(pinnedAnchor, d, true);
}

function unpinMapTooltip() {
  pinnedEventKey = null;
  pinnedAnchor = null;
  pinnedEvent = null;
  mapTooltipEl.classList.remove("pinned", "visible");
}

document.addEventListener("click", (e) => {
  if (!isTooltipPinned()) return;
  if (mapTooltipEl.contains(e.target)) return; // clicks inside the card (e.g. the link) are fine
  unpinMapTooltip();
});

document.addEventListener("keydown", (e) => {
  if (e.key !== "Escape") return;
  unpinMapTooltip();
  clearSpotlight();
});

function positionMapTooltip(event) {
  const bounds = mapSectionEl.getBoundingClientRect();
  const tooltipWidth = mapTooltipEl.offsetWidth || 260;
  const tooltipHeight = mapTooltipEl.offsetHeight || 90;
  const margin = 16;

  let x = event.clientX - bounds.left + 18;
  let y = event.clientY - bounds.top + 18;

  if (x + tooltipWidth + margin > bounds.width) {
    x = event.clientX - bounds.left - tooltipWidth - 18;
  }
  if (y + tooltipHeight + margin > bounds.height) {
    y = event.clientY - bounds.top - tooltipHeight - 18;
  }

  mapTooltipEl.style.left = `${Math.max(margin, x)}px`;
  mapTooltipEl.style.top = `${Math.max(margin, y)}px`;
}

function hideMapTooltip() {
  if (isTooltipPinned()) return; // mouseleave shouldn't dismiss a pinned card
  mapTooltipEl.classList.remove("visible");
}

// Every render is stamped with a token. Dragging the slider fires renders far
// faster than chunks arrive, and without this an early request resolving late
// would repaint the map with a year the user has already scrubbed past.
let renderToken = 0;
let loadingTimer = null;
let pendingSpotlight = null;

function paintYear(rows) {
  // Deselecting a category no longer removes its markers -- they stay on the
  // map greyed out and unlabelled, so you keep the geographic context of what
  // you filtered out and can click one to switch it back on. The events list,
  // by contrast, only shows what's selected.
  const yearEvents = rows.filter((e) => e.year === state.year);
  renderEventsList(yearEvents.filter((e) => state.activeCategories.has(e.category)));
  renderMarkers(yearEvents);

  // Set by jumpToEvent() before the render it triggered. Applied here because
  // the markers only exist now, and consumed so it fires once rather than on
  // every subsequent repaint.
  if (pendingSpotlight) {
    spotlightMarker(pendingSpotlight);
    pendingSpotlight = null;
  }
}

function renderAll() {
  if (!INDEX) return;
  const token = ++renderToken;
  yearBadge.textContent = formatYear(state.year);
  syncUrlToYear();
  updateYearPageLink();

  const n = chunkForYear(state.year);
  const cached = chunkData.get(n);
  if (cached) {
    clearTimeout(loadingTimer);
    eventsListEl.classList.remove("loading");
    paintYear(cached);
    prefetchNeighbours(n);
    return;
  }

  // Only admit to loading if it's slow enough to notice. Most chunk fetches
  // land in well under this, and flashing a spinner for 40ms reads as a glitch.
  clearTimeout(loadingTimer);
  loadingTimer = setTimeout(() => {
    if (token === renderToken) eventsListEl.classList.add("loading");
  }, 180);

  loadChunk(n)
    .then((rows) => {
      if (token !== renderToken) return; // a later scrub owns the view now
      clearTimeout(loadingTimer);
      eventsListEl.classList.remove("loading");
      paintYear(rows);
      prefetchNeighbours(n);
    })
    .catch((err) => {
      if (token !== renderToken) return;
      clearTimeout(loadingTimer);
      eventsListEl.classList.remove("loading");
      console.error(err);
      eventsListEl.innerHTML = `<div class="empty-state">Couldn't load events for ${formatYear(
        state.year
      )}. Check your connection and move the slider to retry.</div>`;
    });
}

// ---- Discover ----

let discoveryResolved = [];
let discoveryCurrent = null;

function initDiscovery() {
  if (!discoveryPromptEl) return;
  if (typeof DISCOVERY_PROMPTS === "undefined") {
    console.warn("Discover: data/discover.js did not load; hiding the panel");
    discoverySectionEl?.setAttribute("hidden", "");
    return;
  }

  // Prompts used to be resolved against the in-memory EVENTS array at startup.
  // With the dataset chunked there is nothing to resolve against, so
  // build-discover.mjs bakes year, category and coordinate into each entry --
  // everything jumpToEvent() and spotlightMarker() need. A prompt is therefore
  // already event-shaped and usable as-is.
  //
  // The cost is that discover.js is now a copy of part of the dataset: regenerate
  // it whenever events.js changes or prompts will jump to a year that has moved.
  discoveryResolved = DISCOVERY_PROMPTS.filter((p) => p.lat != null && p.lng != null);
  const stale = DISCOVERY_PROMPTS.length - discoveryResolved.length;
  if (stale) {
    console.warn(`Discover: ${stale} prompt(s) missing coordinates; rerun scripts/build-discover.mjs`);
  }

  if (!discoveryResolved.length) return;

  showRandomDiscoveryPrompt();

  discoveryRefreshBtnEl?.addEventListener("click", () => {
    showRandomDiscoveryPrompt();
    discoveryRefreshBtnEl.classList.remove("spinning");
    void discoveryRefreshBtnEl.offsetWidth;
    discoveryRefreshBtnEl.classList.add("spinning");
  });

  discoverGoBtnEl?.addEventListener("click", () => {
    if (discoveryCurrent) jumpToEvent(discoveryCurrent);
  });
}

function showRandomDiscoveryPrompt() {
  if (!discoveryResolved.length) return;
  let next = discoveryCurrent;
  if (discoveryResolved.length > 1) {
    while (!next || next.title === discoveryCurrent?.title) {
      next = discoveryResolved[Math.floor(Math.random() * discoveryResolved.length)];
    }
  } else {
    next = discoveryResolved[0];
  }
  discoveryCurrent = next;

  discoveryPromptEl.innerHTML = `Discover what else was going on in the world when <strong>${next.question}</strong> (${formatYear(
    next.year
  )})`;
}

function jumpToEvent(event) {
  // Make sure the event's own category is active so its marker actually
  // renders, then jump the slider to its year.
  state.activeCategories.add(event.category);
  buildCategoryFilters();
  state.year = event.year;
  yearSlider.value = yearToPos(event.year);

  // Hand the spotlight to the render rather than applying it here. Jumping to a
  // distant year usually means fetching that era's chunk, so the marker won't
  // exist yet -- spotlighting now would silently match nothing. paintYear()
  // applies it once the markers are actually on the map.
  pendingSpotlight = event;
  renderAll();

  mapSectionEl?.scrollIntoView({ behavior: "smooth", block: "start" });
}

function spotlightMarker(target) {
  if (!markerLayer) return;
  const key = eventKey(target);
  spotlightKey = key;
  markerLayer
    .selectAll("g.event-marker")
    .filter((d) => eventKey(d) === key)
    .each(function () {
      const g = d3.select(this);
      g.classed("spotlight", false);
      // Force reflow so re-adding the class restarts the CSS animation.
      void this.getBoundingClientRect();
      g.classed("spotlight", true);
    });
}

function clearSpotlight() {
  spotlightKey = null;
  markerLayer?.selectAll("g.event-marker.spotlight").classed("spotlight", false);
}

// ---- Timeline controls ----

yearSlider.addEventListener("input", () => {
  state.year = posToYear(Number(yearSlider.value));
  renderAll();
});

// ---- Go to year ----
//
// The slider spans 12480 BC to 2026 across roughly 900 pixels. That is sixteen
// years per pixel, so no amount of careful dragging lands on 1066 on purpose --
// and since only 17 events fall before 3001 BC, the leftmost sixty per cent of
// the track is nearly empty and drags across it overshoot wildly. This takes
// what someone would actually type instead.
//
// A text input rather than <input type="number"> because the era matters: BC
// years are negative internally but nobody types "-500". Both forms are
// accepted, along with "500 BC", "500BC", "500 b.c.", "500 BCE", "AD 500" and
// "1,200 BC".
//
// The dots and commas are stripped before anything else is matched, which is the
// whole reason this is not a one-line regex. A \b(BCE?)\b tested against "B.C."
// does not match -- the harvester shipped Ōmori Katsuyama, a 2000 BC site, as AD
// 500 for exactly that reason -- and \d{1,4} stops dead at the comma in
// "1,200 BC" and comes back with 200. A silently wrong sign is worse than a
// rejected input, because the map will happily show you the wrong millennium
// without ever looking broken.
function parseYearInput(raw) {
  const lowered = String(raw).trim().toLowerCase();
  // A dot between two digits is a decimal, not era punctuation. Stripping it
  // with the rest would turn "12.5" into the year 125 -- a plausible-looking
  // answer to a question nobody asked.
  if (/\d\.\d/.test(lowered)) return null;
  const s = lowered
    .replace(/[.,]/g, "")
    .replace(/\s+/g, " ")
    // "500 B. C." arrives here as "500 b c". Close the gaps between single
    // letters so the era token is whole again before it is matched.
    .replace(/\b([a-z])\s+(?=[a-z]\b)/g, "$1")
    .trim();
  if (!s) return null;
  // \s* rather than \s+ so "500bc" parses; the era may also lead, as in "AD 500".
  const m = s.match(/^(?:(ad|ce)\s*)?(-?)(\d{1,5})\s*(bce|bc|ce|ad)?$/);
  if (!m) return null;
  const [, leadEra, sign, digits, trailEra] = m;
  const era = trailEra || leadEra || "";
  // "-500 BC" and "AD 500 BC" are contradictions, not years. Guessing which half
  // was meant is exactly the silent-wrong-sign failure this function exists to
  // avoid, so refuse and let the message ask again.
  if (era && sign === "-") return null;
  if (leadEra && trailEra && leadEra !== trailEra) return null;
  const year = Number(digits);
  if (!Number.isFinite(year)) return null;
  return era.startsWith("b") || sign === "-" ? -year : year;
}

const yearJumpForm = document.getElementById("yearJump");
const yearJumpInput = document.getElementById("yearJumpInput");
const yearJumpMsg = document.getElementById("yearJumpMsg");

function stopPlayback() {
  if (!state.playing) return;
  state.playing = false;
  clearInterval(state.playTimer);
  playBtn.querySelector(".icon-play").removeAttribute("hidden");
  playBtn.querySelector(".icon-pause").setAttribute("hidden", "");
}

yearJumpForm.addEventListener("submit", (ev) => {
  ev.preventDefault();
  const wanted = parseYearInput(yearJumpInput.value);
  if (wanted === null) {
    yearJumpMsg.textContent = "Try 1969, 500 BC, or AD 800.";
    yearJumpMsg.classList.add("is-error");
    return;
  }
  const { minYear, maxYear } = INDEX;
  const year = Math.min(Math.max(wanted, minYear), maxYear);
  yearJumpMsg.classList.remove("is-error");
  yearJumpMsg.textContent =
    year === wanted
      ? ""
      : `The timeline runs ${formatYear(minYear)} to ${formatYear(maxYear)} — showing ${formatYear(year)}.`;

  // An explicit jump beats auto-play; leaving the timer running would step off
  // the requested year a second after arriving at it.
  stopPlayback();
  state.year = year;
  yearSlider.value = yearToPos(year);
  renderAll();
  document.getElementById("map").scrollIntoView({ behavior: "smooth", block: "center" });
});

// Enter is the obvious way to use a box like this, and a form with one text
// input and a submit button is supposed to submit on Enter without any help.
// It did not when driven through the browser tools -- a submit listener counted
// zero events from a real keypress -- and rather than ship the most natural
// interaction on the assumption that the automation was at fault, this makes it
// explicit. preventDefault() first, so if implicit submission does fire here for
// real users the form still submits exactly once.
yearJumpInput.addEventListener("keydown", (ev) => {
  if (ev.key !== "Enter") return;
  ev.preventDefault();
  yearJumpForm.requestSubmit();
});

// Clear a stale complaint as soon as the input is touched again, so the error
// does not sit under a box that now reads fine.
yearJumpInput.addEventListener("input", () => {
  yearJumpMsg.textContent = "";
  yearJumpMsg.classList.remove("is-error");
});

stepBackBtn.addEventListener("click", () => {
  const years = getEventYears();
  const prev = [...years].reverse().find((y) => y < state.year);
  if (prev !== undefined) {
    state.year = prev;
    yearSlider.value = yearToPos(prev);
    renderAll();
  }
});

stepForwardBtn.addEventListener("click", () => {
  const years = getEventYears();
  const next = years.find((y) => y > state.year);
  if (next !== undefined) {
    state.year = next;
    yearSlider.value = yearToPos(next);
    renderAll();
  }
});

const playIcon = playBtn.querySelector(".icon-play");
const pauseIcon = playBtn.querySelector(".icon-pause");

playBtn.addEventListener("click", () => {
  state.playing = !state.playing;
  playIcon.toggleAttribute("hidden", state.playing);
  pauseIcon.toggleAttribute("hidden", !state.playing);
  if (state.playing) {
    state.playTimer = setInterval(() => {
      const years = getEventYears();
      const next = years.find((y) => y > state.year);
      if (next !== undefined) {
        state.year = next;
        yearSlider.value = yearToPos(next);
        renderAll();
      } else {
        state.playing = false;
        playIcon.removeAttribute("hidden");
        pauseIcon.setAttribute("hidden", "");
        clearInterval(state.playTimer);
      }
    }, 1200);
  } else {
    clearInterval(state.playTimer);
  }
});

// ---- Init ----

// The static year pages under /year/ link back here as /?year=1969, and BC years
// arrive negative (/?year=-44). Parsed before the range is applied so an
// out-of-dataset year is clamped by the same code that clamps the default.
function yearFromUrl() {
  const raw = new URLSearchParams(location.search).get("year");
  if (raw === null) return null;
  const y = Number(raw);
  return Number.isInteger(y) ? y : null;
}

// Keep the address bar in step with the slider so a view can be linked or
// bookmarked. replaceState, not pushState: scrubbing fires this constantly and
// pushing would bury the back button under hundreds of entries.
let urlSyncTimer = null;
function syncUrlToYear() {
  clearTimeout(urlSyncTimer);
  urlSyncTimer = setTimeout(() => {
    const url = new URL(location.href);
    url.searchParams.set("year", state.year);
    history.replaceState(null, "", url);
  }, 400);
}

function initTimelineRange() {
  const { minYear, maxYear } = INDEX;

  const urlYear = yearFromUrl();
  if (urlYear !== null) state.year = urlYear;

  buildTimelineScale(minYear, maxYear);
  yearSlider.min = 0;
  yearSlider.max = SCALE.positions;
  if (state.year < minYear || state.year > maxYear) {
    state.year = Math.min(Math.max(state.year, minYear), maxYear);
  }
  yearSlider.value = yearToPos(state.year);

  // The compressed stretch is shaded differently so the change of scale is
  // visible rather than something you have to infer from the labels.
  yearSlider.style.setProperty("--split", `${(SCALE.sparsePositions / SCALE.positions) * 100}%`);

  const timelineLabelsEl = document.querySelector(".timeline-labels");
  if (timelineLabelsEl) {
    const stops = 7;
    timelineLabelsEl.innerHTML = "";
    for (let i = 0; i < stops; i++) {
      // Stops are spaced evenly along the TRACK and then converted to years, so
      // they report where the scale actually puts things. Spacing them evenly in
      // years would print a ruler that disagrees with the thumb underneath it.
      const y = posToYear(Math.round((SCALE.positions * i) / (stops - 1)));
      const span = document.createElement("span");
      span.textContent = formatYear(y);
      timelineLabelsEl.appendChild(span);
    }
  }

  if (datasetStatEl) {
    const byCategory = new Map(INDEX.categories.map((c, i) => [c, INDEX.categoryCounts[i]]));
    const breakdown = CATEGORY_ORDER.filter((c) => byCategory.has(c))
      .map((c) => `${c} (${byCategory.get(c)})`)
      .join(", ");
    datasetStatEl.innerHTML = `<strong>${INDEX.total.toLocaleString()} events</strong> spanning ${formatYear(minYear)} &ndash; ${formatYear(maxYear)}.`;
    datasetStatEl.title = breakdown;
  }
}

// ---- Boot ----
//
// Everything downstream reads INDEX, so the index has to land before any of it
// runs. The world map and the first year's chunk are then fetched in parallel
// by initMap() and renderAll().
async function init() {
  try {
    await loadIndex();
  } catch (err) {
    console.error(err);
    eventsListEl.innerHTML = `<div class="empty-state">Couldn't load the timeline data. Please reload the page.</div>`;
    return;
  }
  initTimelineRange();
  buildCategoryFilters();
  initMap();
  initDiscovery();
}

init();
